In [111]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [112]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [113]:
data =sns.load_dataset('mpg')
print(data.head(3))

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  


In [114]:
df = pd.read_csv('D:/DS topmentor 2023/mpg.csv')
print(data.head(3))

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  


In [115]:
##### creat a copy of your actual data
mpg_data = data.copy()
print(mpg_data.head(2))

    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  


In [116]:
##### Checking the basic information of yr data
print(mpg_data.shape)

(398, 9)


In [117]:
print(mpg_data.dtypes)

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model_year        int64
origin           object
name             object
dtype: object


In [118]:
print(mpg_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB
None


In [119]:
print(mpg_data.columns)

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')


In [120]:
#### fill the null values with 0
mpg_data['horsepower'] = mpg_data['horsepower'].fillna(0)

In [121]:
print(mpg_data.isnull().sum())

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64


In [122]:
# Simple Liener Regression, predictive model for prediction milage per gallon, based on weight.
y = mpg_data['mpg']
print(y)

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64


In [123]:
x = mpg_data['weight']
print(x)

0      3504
1      3693
2      3436
3      3433
4      3449
       ... 
393    2790
394    2130
395    2295
396    2625
397    2720
Name: weight, Length: 398, dtype: int64


In [124]:
# before creating model devide the dataset ratio is 80:20, process-1.
mpg_data.shape

(398, 9)

In [125]:
398*0.8

318.40000000000003

In [126]:
from sklearn.model_selection import train_test_split

In [127]:
training, testing = train_test_split(mpg_data, test_size=0.2)

In [128]:
training.shape

(318, 9)

In [129]:
testing.shape

(80, 9)

In [130]:
### Process-2
from sklearn.model_selection import train_test_split

In [131]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [132]:
x_train.shape, y_train.shape

((318,), (318,))

In [133]:
x_test.shape, y_test.shape

((80,), (80,))

In [134]:
### importing of libraries
import pandas as pd

In [135]:
data = pd.DataFrame({'age' : [23,25,26,27,28,28,22,25], 'height':[5.2,4.5,5.5,6.2,6.3,5.2,5.8,5.1]})
print(data)

   age  height
0   23     5.2
1   25     4.5
2   26     5.5
3   27     6.2
4   28     6.3
5   28     5.2
6   22     5.8
7   25     5.1


In [136]:
x = data['age'].values
x

array([23, 25, 26, 27, 28, 28, 22, 25], dtype=int64)

In [137]:
## in simple linear regrattion reshape the value in vertical, bcs simple lr not understand horizontal.array.
x = data['age'].values.reshape(-1,1)# (-1,1) is in single array.
x

array([[23],
       [25],
       [26],
       [27],
       [28],
       [28],
       [22],
       [25]], dtype=int64)

In [138]:
y = data['height'].values
y

array([5.2, 4.5, 5.5, 6.2, 6.3, 5.2, 5.8, 5.1])

In [139]:
## in simple linear regrattion reshape the value in vertical, bcs simple lr not understand horizontal.array.
y = data['height'].values.reshape(-1,1)# (-1,1) is in single array.
y


array([[5.2],
       [4.5],
       [5.5],
       [6.2],
       [6.3],
       [5.2],
       [5.8],
       [5.1]])

In [140]:
from sklearn.linear_model import LinearRegression

In [141]:
lr = LinearRegression()
lr.fit(x,y)

LinearRegression()

In [142]:
pred = lr.predict(x)
pred

array([[5.27647059],
       [5.43529412],
       [5.51470588],
       [5.59411765],
       [5.67352941],
       [5.67352941],
       [5.19705882],
       [5.43529412]])